# Generated by Django 3.1.5 on 2021-01-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('company_name', models.CharField(max_length=50, verbose_name='Company Name')),
                ('ticker_symbol', models.CharField(max_length=5, verbose_name='Ticker Symbol')),
                ('current_stock_price', models.FloatField(verbose_name='Current Stock Price')),
                ('open_price', models.FloatField(primary_key=True, serialize=False, verbose_name='Open Price')),
            ],
            options={
                'ordering': ['ticker_symbol'],
            },
        ),
    ]
