# Generated by Django 3.1.5 on 2021-01-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='open_price',
            field=models.FloatField(verbose_name='Open Price'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker_symbol',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Ticker Symbol'),
        ),
    ]
